import type { Config } from "tailwindcss";

const config: Config = {
	content: ["./src/**/*.{ts,tsx,mdx}"],
	theme: {
		extend: {
			colors: {
				black: "#1f2025",
				identity: {
					100: "#dae0fe",
					200: "#b5c1fe",
					300: "#7386f9",
					400: "#465df6",
					500: "#3345d3",
					600: "#2331b1",
					700: "#16218e",
					800: "#0d1576",
				},
			},
			fontFamily: {
				pretendard: [
					"Pretendard Variable",
					"Pretendard",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
				sbaggro: [
					"SBAggro",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
				hanamdaum: [
					"HANAMDAUM",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
			},
		},
	},
	plugins: [],
};
export default config;
