import type { Config } from "tailwindcss";

const config: Config = {
	content: ["./src/**/*.{ts,tsx,mdx}"],
	theme: {
		extend: {
			colors: {
				black: "#1f2025",
			},
			fontFamily: {
				pretendard: [
					"Pretendard Variable",
					"Pretendard",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
				sbaggro: [
					"SBAggro",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
				hanamdaum: [
					"HANAMDAUM",
					"-apple-system",
					"BlinkMacSystemFont",
					"system-ui",
					"Roboto",
					"Helvetica Neue",
					"Segoe UI",
					"Apple SD Gothic Neo",
					"Noto Sans KR",
					"Malgun Gothic",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"sans-serif",
				],
			},
		},
	},
	plugins: [],
};
export default config;
