name: Deploy Website

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy to AWS (main)
        if: github.ref_name == 'main'
        run: |
          corepack enable && \
          curl -fsSL https://ion.sst.dev/install | bash && \
          pnpm install && \
          pnpm deploy

      - name: Deploy to AWS (develop)
        # if: github.ref_name == 'develop'
        run: |
          corepack enable
          curl -fsSL https://ion.sst.dev/install | bash
          pnpm install
          pnpm deploy:dev
