name: Deploy Website (main)

on:
  push:
    # branches:
    #   - develop
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy to AWS
        run: |
          corepack enable
          curl -fsSL https://ion.sst.dev/install | bash
          pnpm install
          sst deploy --stage develop
